version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY}server
    build:
      context: .
      dockerfile: ShowsApiMicroservice/ApiServer/Dockerfile
    depends_on:
      - db
  db:
      image: "microsoft/mssql-server-linux"
      ports:
        - "1433:1433"
      environment:
          SA_PASSWORD: "TestPassword123"
          ACCEPT_EULA: "Y"
