version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY}server
    build:
      context: .
      dockerfile: ShowsApiMicroservice/ApiServer/Dockerfile
    depends_on:
      - showsdb
      - rabbit
  showsdb:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: TestPassword123
      ACCEPT_EULA: Y
      mongo:
  tvmazescraper.host:
    image: ${DOCKER_REGISTRY}tvmazescraperhost
    build:
      context: .
      dockerfile: TvMazeScraperMicroservice/TvMazeScraper.Host/Dockerfile
    depends_on:
      - tvmazedb
      - server
      - rabbit
  tvmazedb:
    image: mongo
    restart: always
  rabbit:
    image: "rabbitmq"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "TestUser"
      RABBITMQ_DEFAULT_PASS: "TestPassword"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

