namespace TvMazeScraper.Infrastructure.Interface
{
	public enum StringsEnum
	{
		ERROR_SAMPLE,
		WARNING_SAMPLE,
		SCRAPER_HOSTED_SERVICE_STARTING,
		SCRAPER_HOSTED_SERVICE_STARTED,
		SCRAPER_HOSTED_SERVICE_STOPED,
		SCRAPER_HOSTED_SERVICE_IMPORT_STARTED,
		INVALID_TVMAZE_DATA_RECEIVED,
		ERROR_FAILED_ADD_IMPORT_INFO,
		STARTED_IMPORT_NEW_TVMAZE_SHOWS,
		START_PROCESS_IMPORT_RESULTS
	}
}