namespace Infrastructure.Interface
{
	public enum StringsEnum
	{
		API_INVALID_SHOW_MODEL_ERROR,
		ERROR_SAMPLE,
		WARNING_SAMPLE,
		ARGUMENT_ERROR_SKIP_TAKE,
		DATABASE_ERROR_SAMPLE,
		COMMUNICATION_STARTED,
		COMMUNICATION_ENDED,
		START_SHOW_IMPORT_SINGLE_BLOCK,
		FAILED_SHOW_IMPORT_SINGLE_BLOCK,
		START_SHOW_IMPORT_ONE_BY_ONE,
		START_PROCESS_IMPORT_REQUESTS
	}
}